export const GET_PRODUCTS_LOADING = "GET_PRODUCTS_LOADING";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

<<<<<<< HEAD
export const GET_PRODUCT_LOADING = 'GET_PRODUCT_LOADING';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR';

export const ADD_AND_DELETE_PRODUCT_IN_CART = 'ADD_AND_DELETE_PRODUCT_IN_CART';
export const GET_CART = 'GET_CART';
=======
export const GET_PRODUCT_LOADING = "GET_PRODUCT_LOADING";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

export const ADD_AND_DELETE_PRODUCT_IN_CART = "ADD_AND_DELETE_PRODUCT_IN_CART";
export const GET_CART = "GET_CART";
>>>>>>> c3fd94efd0b93d2e59985de06a42c2af4368a2c3
